import { HorizontalBox, AboutSlint } from "std-widgets.slint";
import { Page } from "page.slint";
import { GlobalState } from "../global_state.slint";

export component AboutPage inherits Page {
    title: @tr("About");
    padding-top: 50px;

    Text {
        text: "Turbo Clicker";
        horizontal-alignment: center;
    }

    Text {
        text: @tr("Version: v{}", GlobalState.version);
        horizontal-alignment: center;
    }

    Text {
        text: @tr("Commit: {}", GlobalState.commit);
        horizontal-alignment: center;
    }

    // Spacer
    Rectangle { }

    HorizontalBox {
        alignment: center;
        AboutSlint {
            height: 100px;
        }
    }
}
