import { Page } from "page.slint";
import { Button, VerticalBox } from "std-widgets.slint";

export component CounterPage inherits Page {
    title: @tr("Click Counter");

    property <int> counter: 0;
    VerticalBox {
        Text {
            text: @tr("Counter: {}", root.counter);
        }

        Button {
            text: @tr("Click Me");
            clicked => {
                root.counter += 1;
            }
        }

        Button {
            text: @tr("Reset Counter");
            clicked => {
                root.counter = 0;
            }
        }
    }
}
