import { Page } from "page.slint";
import { GlobalState } from "../global_state.slint";
import { Switch, Button } from "std-widgets.slint";

export component SettingsPage inherits Page {
    title: @tr("Settings");
    padding: 10px;
    alignment: start;

    Switch {
        text: @tr("Dark Mode");
        checked <=> GlobalState.dark-mode;
    }
    Button {
        text: @tr("Configure Hotkey");
        clicked => {
            GlobalState.configure-hotkey();
        }
    }
}
