import { Page } from "page.slint";
import { GlobalState } from "../global_state.slint";
import { Switch, Palette, HorizontalBox } from "std-widgets.slint";

export component SettingsPage inherits Page {
    title: "Settings";
    padding: 10px;
    alignment: start;

    Switch {
        text: "Dark Mode";
        checked <=> GlobalState.dark-mode;
    }

    // Spacer
    Rectangle { }

    Text {
        text: "Hotkey:";
    }

    Rectangle {
        background: Palette.alternate-background;

        property <[string]> hotkey: GlobalState.hotkey;

        HorizontalBox {
            alignment: center;
            spacing: 0px;
            for key[i] in hotkey: Text {
                text: i == hotkey.length - 1 ? "'" + key + "'" : "'" + key + "' + ";
            }
        }
    }
}
