# Generated by rust2rpm 27
%bcond check 1

# prevent library files from being installed
%global cargo_install_lib 0

Name:           turbo-clicker
Version:        0
Release:        %autorelease
Summary:        GUI based auto-clicker for Linux

%global package_id io.github.heathcliff26.%{name}

License:        Apache-2.0
URL:            https://github.com/heathcliff26/turbo-clicker
Source:         %{url}/archive/refs/tags/v%{version}.tar.gz

Requires: polkit

BuildRequires: cargo >= 1.87

%global _description %{expand:
GUI based auto-clicker for Linux. It uses uinput and should thus work
independently of wayland or x11.}

%description %{_description}

%prep
%autosetup -n turbo-clicker-%{version} -p1

%build
cargo build --release

%install
install -D -m 755 target/release/%{name} %{buildroot}/%{_bindir}/%{name}
install -D -m 755 packages/%{name}-pkexec-wrapper.sh %{buildroot}/%{_libexecdir}/%{name}-pkexec-wrapper.sh
install -D -m 644 packages/%{package_id}.desktop %{buildroot}/%{_datadir}/applications/%{package_id}.desktop
install -D -m 644 packages/%{package_id}.svg %{buildroot}/%{_datadir}/icons/hicolor/scalable/apps/%{package_id}.svg
install -D -m 644 %{package_id}.metainfo.xml %{buildroot}/%{_datadir}/metainfo/%{package_id}.metainfo.xml
mkdir -p %{buildroot}/%{_sharedstatedir}/%{package_id}

%preun
if [ $1 -eq 0 ]; then
    rm %{_sharedstatedir}/%{package_id}/*.json
fi

%files
%license LICENSE
%doc README.md
%{_bindir}/%{name}
%{_libexecdir}/%{name}-pkexec-wrapper.sh
%{_datadir}/applications/%{package_id}.desktop
%{_datadir}/icons/hicolor/scalable/apps/%{package_id}.svg
%{_datadir}/metainfo/%{package_id}.metainfo.xml
%dir %{_sharedstatedir}/%{package_id}

%changelog
%autochangelog
