import { Button, VerticalBox, HorizontalBox, SpinBox, Slider, CheckBox, Palette, AboutSlint } from "std-widgets.slint";
import { GlobalState } from "global_state.slint";
import { MainPage, AboutPage } from "pages/pages.slint";
import { NavBar } from "nav-bar.slint";

export { GlobalState }

export component AppWindow inherits Window {
    title: "Turbo Clicker";
    icon: @image-url("../packages/io.github.heathcliff26.turbo-clicker.svg");
    default-font-size: 18px;
    preferred-height: 400px;
    preferred-width: 500px;

    VerticalLayout {
        nav-bar := NavBar {
            model: ["App", "About"];
        }

        if(nav-bar.current-item == 0): MainPage { }
        if(nav-bar.current-item == 1): AboutPage { }
    }
}
