import { Palette } from "std-widgets.slint";

export global GlobalState {
    // Note: Default values are set in the backend.

    // The delay between clicks in milliseconds.
    in-out property <int> delay: 20;
    // The delay in seconds before starting the auto-click.
    in-out property <int> start-delay: 1;
    in-out property <bool> use-start-delay: true;
    // The time to wait in seconds before stopping the auto-click.
    in-out property <int> duration: 1;
    in-out property <bool> use-duration: true;

    in-out property <bool> dark-mode: true;
    in-out property <int> selected-language: 0;

    // Application version information. Needs to be populated from backend.
    in-out property <string> version: "-";
    in-out property <string> commit: @tr("unknown");

    callback start-auto-click();
    callback settings-changed();
    callback configure-hotkey();
    callback change-language();

    public function setDelay(value: int) {
        if (value < 20) {
            delay = 20;
        } else if (value > 1000) {
            delay = 1000;
        } else {
            delay = Math.floor(value);
        }
        settings-changed();
    }

    public function setColorScheme() {
        Palette.color-scheme = dark-mode ? ColorScheme.dark : ColorScheme.light;
    }

    changed dark-mode => {
        setColorScheme();
        settings-changed();
    }
}
